name: "Update Changelog"
on:
  push:
    branches:
      - master

jobs:
  update-changelog:
    concurrency: changelog
    runs-on: ubuntu-20.04
    if: github.repository == 'cmss13-devs/cmss13'
    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyyaml pygithub pytz
        sudo apt-get install  dos2unix
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch Changelog
      run: |
        python .github/ss13_fetchchangelog.py html/changelogs
      env:
        REPO: ${{ github.repository }}
    - name: Update Changelog
      run: |
        python .github/ss13_genchangelog.py html/changelogs
    - name: Commit
      run: |
        git pull origin master
        git config --local user.email "action@github.com"
        git config --local user.name "Changelogs"
        git add html/changelogs/archive
        git commit -m "Automatic changelog compile [ci skip]" -a || true
    - name: "Push"
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
